name: run-tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      TEST_STORAGE_DSN: "postgres://undertaker:undertaker@localhost:12345/undertaker?sslmode=disable"

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Run tests
      run: docker-compose -f docker-compose.ci.yaml up --exit-code-from undertaker
